import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { IwakFont } from '@/app/public/fonts/fonts';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'drink-iwak',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning
				className={cn(`${inter.className} ${IwakFont.variable}`)}>
				{children}
			</body>
		</html>
	);
}
